name: CI run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: update packages
      run: sudo apt update

    # set up Basic
    - name : install freebasic
      run : |
        sudo apt install gcc libncurses5-dev libffi-dev libgl1-mesa-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxpm-dev
        sudo apt install libtinfo5
        curl https://sourceforge.net/projects/fbc/files/Binaries%20-%20Linux/FreeBASIC-1.07.1-linux-x86_64.tar.gz/download > FreeBASIC-1.07.1-linux-x86_64.tar.gz
        tar -xvvf FreeBASIC-1.07.1-linux-x86_64.tar.gz
        sudo ./FreeBASIC-1.07.1-linux-x86_64/install.sh -i


    # Runs the main script script
    - name: Run script
      run: ./run.sh

      